version: '3.9'

services:

  gramine:
    image: gramine
    build:
      context: ./
      dockerfile: Dockerfile
      # args:
    environment:
      SGX: 1
    volumes:
      - ./untrustedhost:/root/untrustedhost
      - ./enclave_data:/root/enclave_data
      - /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket
    devices:
      - /dev/sgx_enclave
      - /dev/sgx_provision
    network_mode: host
    init: true